project:
  type: website
  output-dir: docs

website:
  title: "stats-notes"
  description: "Study notes on statistics"
  sidebar:
    contents: auto
    tools:
      - icon: github
        href: https://github.com/hamzakat/stats-notes/
    collapse-level: 1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true
